### ISSUE TITLE
Userscripts end in .user.js not plain .js

### ISSUE THREAD

**Issue by Martii** [rainame/madoka#1]
Use `git mv dmzj-comic.js dmzj-comic.user.js`; then push to GitHub; then reimport to OUJS.

Thanks,
OUJS Admin

---

Translation courtesy of Google with Chinese Simplified

> 使用 `git mv dmzj-comic.js dmzj-comic.user.js`; 然后推送给GitHub; 然后重新导入OUJS。
>
> 谢谢，
> OUJS Admin

**Comment by rainame** [comment]
Done.

Thanks.
